### ISSUE TITLE
Updating patient's date of birth will break server

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#3049]
If you try to edit a patient and only update their date of birth, the following error is thrown in the server:
```sh
  errors #interceptor() TypeError: Cannot read property 'trim' of undefined
  errors     at update (/home/jniles/code/2.x/bin/server/controllers/medical/patients/index.js:190:43)
  errors     at Layer.handle [as handle_request] (/home/jniles/code/2.x/node_modules/express/lib/router/layer.js:95:5)
  errors     at next (/home/jniles/code/2.x/node_modules/express/lib/router/route.js:137:13)
  errors     at Route.dispatch (/home/jniles/code/2.x/node_modules/express/lib/router/route.js:112:3)
  errors     at Layer.handle [as handle_request] (/home/jniles/code/2.x/node_modules/express/lib/router/layer.js:95:5)
  errors     at /home/jniles/code/2.x/node_modules/express/lib/router/index.js:281:22
  errors     at param (/home/jniles/code/2.x/node_modules/express/lib/router/index.js:354:14)
  errors     at param (/home/jniles/code/2.x/node_modules/express/lib/router/index.js:365:14)
  errors     at Function.process_params (/home/jniles/code/2.x/node_modules/express/lib/router/index.js:410:3)
  errors     at next (/home/jniles/code/2.x/node_modules/express/lib/router/index.js:275:10)
  errors     at app.use (/home/jniles/code/2.x/bin/server/config/express.js:106:7)
  errors     at Layer.handle [as handle_request] (/home/jniles/code/2.x/node_modules/express/lib/router/layer.js:95:5)
  errors     at trim_prefix (/home/jniles/code/2.x/node_modules/express/lib/router/index.js:317:13)
  errors     at /home/jniles/code/2.x/node_modules/express/lib/router/index.js:284:7
  errors     at Function.process_params (/home/jniles/code/2.x/node_modules/express/lib/router/index.js:335:12)
  errors     at next (/home/jniles/code/2.x/node_modules/express/lib/router/index.js:275:10) +0ms
```

It looks like we are trying to normalize the patient's name via `.trim()` and it is failing when the property doesn't exist.

**Comment by jniles** [comment]
I'll tackle this.
