### ISSUE TITLE
does not work with MySQL 8

### ISSUE THREAD

**Issue by individual-it** [third-culture-software/bhima#4393]
I just tried to run e2e tests of bhima on Ubuntu 20.04 (that comes with MySQL 8)

Bhima uses the `PASSWORD()` mysql function, that is deprecated in MySQL 8

see https://stackoverflow.com/a/52320680/4501350

```
[17:02:43] I/local - Selenium standalone server started at http://127.0.0.1:58733/wd/hub
  errors #interceptor() Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '('superuser')
  errors       AND project_permission.project_id = 1' at line 8
  errors     at Query.Sequence._packetToError (/home/artur/www/IMA-WorldHealth/bhima/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
  errors     at Query.ErrorPacket (/home/artur/www/IMA-WorldHealth/bhima/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
  errors     at Protocol._parsePacket (/home/artur/www/IMA-WorldHealth/bhima/node_modules/mysql/lib/protocol/Protocol.js:291:23)
  errors     at Parser._parsePacket (/home/artur/www/IMA-WorldHealth/bhima/node_modules/mysql/lib/protocol/Parser.js:433:10)
  errors     at Parser.write (/home/artur/www/IMA-WorldHealth/bhima/node_modules/mysql/lib/protocol/Parser.js:43:10)
  errors     at Protocol.write (/home/artur/www/IMA-WorldHealth/bhima/node_modules/mysql/lib/protocol/Protocol.js:38:16)
  errors     at Socket.<anonymous> (/home/artur/www/IMA-WorldHealth/bhima/node_modules/mysql/lib/Connection.js:88:28)
  errors     at Socket.<anonymous> (/home/artur/www/IMA-WorldHealth/bhima/node_modules/mysql/lib/Connection.js:526:10)
  errors     at Socket.emit (events.js:310:20)
  errors     at addChunk (_stream_readable.js:286:12)
  errors     at readableAddChunk (_stream_readable.js:268:9)
  errors     at Socket.Readable.push (_stream_readable.js:209:10)
  errors     at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
  errors     --------------------
  errors     at Protocol._enqueue (/home/artur/www/IMA-WorldHealth/bhima/node_modules/mysql/lib/protocol/Protocol.js:144:48)
  errors     at PoolConnection.query (/home/artur/www/IMA-WorldHealth/bhima/node_modules/mysql/lib/Connection.js:198:25)
  errors     at /home/artur/www/IMA-WorldHealth/bhima/bin/server/lib/db/index.js:87:18
  errors     at Ping.onOperationComplete (/home/artur/www/IMA-WorldHealth/bhima/node_modules/mysql/lib/Pool.js:110:5)
  errors     at Ping.<anonymous> (/home/artur/www/IMA-WorldHealth/bhima/node_modules/mysql/lib/Connection.js:526:10)
  errors     at Ping._callback (/home/artur/www/IMA-WorldHealth/bhima/node_modules/mysql/lib/Connection.js:488:16)
  errors     at Ping.Sequence.end (/home/artur/www/IMA-WorldHealth/bhima/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
  errors     at Ping.Sequence.OkPacket (/home/artur/www/IMA-WorldHealth/bhima/node_modules/mysql/lib/protocol/sequences/Sequence.js:92:8)
  errors     at Protocol._parsePacket (/home/artur/www/IMA-WorldHealth/bhima/node_modules/mysql/lib/protocol/Protocol.js:291:23)
  errors     at Parser._parsePacket (/home/artur/www/IMA-WorldHealth/bhima/node_modules/mysql/lib/protocol/Parser.js:433:10)
  errors     at Parser.write (/home/artur/www/IMA-WorldHealth/bhima/node_modules/mysql/lib/protocol/Parser.js:43:10)
  errors     at Protocol.write (/home/artur/www/IMA-WorldHealth/bhima/node_modules/mysql/lib/protocol/Protocol.js:38:16)
  errors     at Socket.<anonymous> (/home/artur/www/IMA-WorldHealth/bhima/node_modules/mysql/lib/Connection.js:88:28)
  errors     at Socket.<anonymous> (/home/artur/www/IMA-WorldHealth/bhima/node_modules/mysql/lib/Connection.js:526:10)
  errors     at Socket.emit (events.js:310:20)
  errors     at addChunk (_stream_readable.js:286:12) {
  errors   code: 'ER_PARSE_ERROR',
  errors   errno: 1064,
  errors   sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '('superuser')\n" +
  errors     "      AND project_permission.project_id = 1' at line 8",
  errors   sqlState: '42000',
  errors   index: 0,
  errors   sql: 'SELECT\n' +
  errors     '      user.id, user.username, user.display_name, user.email, user.deactivated,\n' +
  errors     '      project.enterprise_id , project.id AS project_id\n' +
  errors     '    FROM user\n' +
  errors     '    JOIN project_permission JOIN project ON user.id = project_permission.user_id\n' +
  errors     '      AND project.id = project_permission.project_id\n' +
  errors     '    WHERE\n' +
  errors     "      user.username = 'superuser' AND user.password = PASSWORD('superuser')\n" +
  errors     '      AND project_permission.project_id = 1;'
  errors } +0ms

**Comment by jniles** [comment]
@individual-it thanks for this bug report.

Yes indeed, we don't have any support for MySQL 8 at this time.  Along with the removal of the password function, this issue also scared us off: https://github.com/mysqljs/mysql/pull/1962.  We don't really have the engineering resources to dedicate to making it compatible with MySQL 8 at present but would welcome any help.

A long time ago, we discussed moving to bcrypt (https://github.com/IMA-WorldHealth/bhima/issues/1754).  In fact, there are a few commits to that end: https://github.com/IMA-WorldHealth/bhima/commit/89df47e4dcef32f2f686a23a3907aae049199f10 on the branch `feature-bcrypt`.  Note that the branch is over two years old now, so we'd probably want to cherry-pick them to merge them in.

If you would like to take a look at getting this working, we'd welcome a pull request!

**Comment by individual-it** [comment]
for now I fixed the docs ;-) https://github.com/IMA-WorldHealth/bhima/pull/4440

**Comment by jniles** [comment]
Closing this in favor of #4463 since the documentation changes have landed.
