### ISSUE TITLE
SemaphoreCI tests flake out at postToGeneralLedger()

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#4964]
The SemaphoreCI tests seem to flake out at the postToGeneralLedger() unit tests with a date column issue.  I would say they fail about ... 10-20% of the time.  I'm not sure what would be causing this.

[Here is an example failure](https://ima-worldhealth.semaphoreci.com/jobs/474044b2-1687-4fbf-9ddc-7a69db2009ce).

Here is the error produced: 

```
   ✓ POST /journal/trialbalance returns summary information grouped by account00:24
  errors #interceptor() Error: ER_BAD_NULL_ERROR: Column 'date' cannot be null00:24
  errors     at Query.Sequence._packetToError (/home/semaphore/bhima/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)00:24
  errors     at Query.ErrorPacket (/home/semaphore/bhima/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)00:24
  errors     at Protocol._parsePacket (/home/semaphore/bhima/node_modules/mysql/lib/protocol/Protocol.js:291:23)00:24
  errors     at Parser._parsePacket (/home/semaphore/bhima/node_modules/mysql/lib/protocol/Parser.js:433:10)00:24
  errors     at Parser.write (/home/semaphore/bhima/node_modules/mysql/lib/protocol/Parser.js:43:10)00:24
  errors     at Protocol.write (/home/semaphore/bhima/node_modules/mysql/lib/protocol/Protocol.js:38:16)00:24
  errors     at Socket.<anonymous> (/home/semaphore/bhima/node_modules/mysql/lib/Connection.js:88:28)00:24
  errors     at Socket.<anonymous> (/home/semaphore/bhima/node_modules/mysql/lib/Connection.js:526:10)00:24
  errors     at Socket.emit (events.js:315:20)​00:24
  errors     at addChunk (_stream_readable.js:295:12)​00:24
  errors     at readableAddChunk (_stream_readable.js:271:9)​00:24
  errors     at Socket.Readable.push (_stream_readable.js:212:10)​00:24
  errors     at TCP.onStreamRead (internal/stream_base_commons.js:186:23)​00:24
  errors     --------------------00:24
  errors     at Protocol._enqueue (/home/semaphore/bhima/node_modules/mysql/lib/protocol/Protocol.js:144:48)00:24
  errors     at PoolConnection.query (/home/semaphore/bhima/node_modules/mysql/lib/Connection.js:198:25)00:24
  errors     at queryConnection (/home/semaphore/bhima/bin/server/lib/db/transaction.js:14:28)00:24
  errors     at /home/semaphore/bhima/bin/server/lib/db/transaction.js:127:4800:24
  errors     at Array.map (<anonymous>)00:24
  errors     at Query.<anonymous> (/home/semaphore/bhima/bin/server/lib/db/transaction.js:127:34)00:24
  errors     at Query.<anonymous> (/home/semaphore/bhima/node_modules/mysql/lib/Connection.js:526:10)00:24
  errors     at Query._callback (/home/semaphore/bhima/node_modules/mysql/lib/Connection.js:488:16)00:24
  errors     at Query.Sequence.end (/home/semaphore/bhima/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)00:24
  errors     at Query._handleFinalResultPacket (/home/semaphore/bhima/node_modules/mysql/lib/protocol/sequences/Query.js:149:8)00:24
  errors     at Query.OkPacket (/home/semaphore/bhima/node_modules/mysql/lib/protocol/sequences/Query.js:74:10)00:24
  errors     at Protocol._parsePacket (/home/semaphore/bhima/node_modules/mysql/lib/protocol/Protocol.js:291:23)00:24
  errors     at Parser._parsePacket (/home/semaphore/bhima/node_modules/mysql/lib/protocol/Parser.js:433:10)00:24
  errors     at Parser.write (/home/semaphore/bhima/node_modules/mysql/lib/protocol/Parser.js:43:10)00:24
  errors     at Protocol.write (/home/semaphore/bhima/node_modules/mysql/lib/protocol/Protocol.js:38:16)00:24
  errors     at Socket.<anonymous> (/home/semaphore/bhima/node_modules/mysql/lib/Connection.js:88:28)00:24
  errors     at Socket.<anonymous> (/home/semaphore/bhima/node_modules/mysql/lib/Connection.js:526:10)00:24
  errors     at Socket.emit (events.js:315:20)​00:24
  errors     at addChunk (_stream_readable.js:295:12)​00:24
  errors     at readableAddChunk (_stream_readable.js:271:9)​00:24
  errors     at Socket.Readable.push (_stream_readable.js:212:10)​00:24
  errors     at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {00:24
  errors   code: 'ER_BAD_NULL_ERROR',00:24
  errors   errno: 1048,00:24
  errors   sqlMessage: "Column 'date' cannot be null",00:24
  errors   sqlState: '23000',00:24
  errors   index: 0,00:24
  errors   sql: 'CALL PostToGeneralLedger();'​00:24
  errors } +19ms​00:24
    1) POST /journal/transactions posts the a transaction to general_ledger and removes it from the journal00:24
​```

**Comment by jniles** [comment]
@kwilu claim.

**Comment by jniles** [comment]
So ... one thing I have discovered debugging this:

[Our posting_journal allows the `description` column to be NULL](https://github.com/IMA-WorldHealth/bhima/blob/master/server/models/schema.sql#L1295) but [our general_ledger does not allow the `description` to be NULL](https://github.com/IMA-WorldHealth/bhima/blob/master/server/models/schema.sql#L655).

Is this what we want?
