### ISSUE TITLE
(bug) posting journal columns throws JS error

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#535]
**Steps to reproduce**
1. Log into the app
2. Access the posting journal page

**Result**
The console displays the following error message:

``` js
vendor.min.js:122 TypeError: Cannot read property 'hideColumn' of null
    at https://localhost:8080/js/bhima.min.js:18935:45
    at Array.forEach (native)
    at h.<anonymous> (https://localhost:8080/js/bhima.min.js:18931:21)
    at https://localhost:8080/js/vendor.min.js:8415:30736
    at m.$emit (https://localhost:8080/js/vendor.min.js:152:47)
    at Object.f.raise.(anonymous function) [as renderingComplete] (https://localhost:8080/js/vendor.min.js:8415:31771)
    at p.renderingComplete (https://localhost:8080/js/vendor.min.js:8415:25782)
    at Object.post (https://localhost:8080/js/vendor.min.js:8415:2958)
    at https://localhost:8080/js/vendor.min.js:21:56
    at https://localhost:8080/js/vendor.min.js:85:481
```

**Expected Result**
No error.

**Comment by jniles** [comment]
I'll take this one.
