### ISSUE TITLE
If a row is referenced in a fee_center_distribution, it cannot be unposted

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#5572]
If a row is referenced in a `fee_center_distribution`, the unposting process (which is copying from the general_ledger to the journal) will fail.  This is somewhat unexpected.  Since the fee_center work is an analysis, we should just delete the reference and be done with it. 

Here is the raw error:
```sh
  errors #interceptor() Error: ER_ROW_IS_REFERENCED_2: Cannot delete or update a parent row: a foreign key constraint fails (`bhima_test`.`fee_center_distribution`, CONSTRAINT `fee_center_distribution__general_ledger` FOREIGN KEY (`row_uuid`) REFERENCES `general_ledger` (`uuid`))
  errors     at Query.Sequence._packetToError (/home/jniles/code/bhima/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
  errors     at Query.ErrorPacket (/home/jniles/code/bhima/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
  errors     at Protocol._parsePacket (/home/jniles/code/bhima/node_modules/mysql/lib/protocol/Protocol.js:291:23)
  errors     at Parser._parsePacket (/home/jniles/code/bhima/node_modules/mysql/lib/protocol/Parser.js:433:10)
  errors     at Parser.write (/home/jniles/code/bhima/node_modules/mysql/lib/protocol/Parser.js:43:10)
  errors     at Protocol.write (/home/jniles/code/bhima/node_modules/mysql/lib/protocol/Protocol.js:38:16)
  errors     at Socket.<anonymous> (/home/jniles/code/bhima/node_modules/mysql/lib/Connection.js:88:28)
  errors     at Socket.<anonymous> (/home/jniles/code/bhima/node_modules/mysql/lib/Connection.js:526:10)
  errors     at Socket.emit (events.js:315:20)
  errors     at addChunk (internal/streams/readable.js:309:12)
  errors     at readableAddChunk (internal/streams/readable.js:284:9)
  errors     at Socket.Readable.push (internal/streams/readable.js:223:10)
  errors     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
  errors     --------------------
  errors     at Protocol._enqueue (/home/jniles/code/bhima/node_modules/mysql/lib/protocol/Protocol.js:144:48)
  errors     at PoolConnection.query (/home/jniles/code/bhima/node_modules/mysql/lib/Connection.js:198:25)
  errors     at queryConnection (/home/jniles/code/bhima/bin/server/lib/db/transaction.js:14:28)
  errors     at /home/jniles/code/bhima/bin/server/lib/db/transaction.js:127:48
  errors     at Array.map (<anonymous>)
  errors     at Query.<anonymous> (/home/jniles/code/bhima/bin/server/lib/db/transaction.js:127:34)
  errors     at Query.<anonymous> (/home/jniles/code/bhima/node_modules/mysql/lib/Connection.js:526:10)
  errors     at Query._callback (/home/jniles/code/bhima/node_modules/mysql/lib/Connection.js:488:16)
  errors     at Query.Sequence.end (/home/jniles/code/bhima/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
  errors     at Query._handleFinalResultPacket (/home/jniles/code/bhima/node_modules/mysql/lib/protocol/sequences/Query.js:149:8)
  errors     at Query.OkPacket (/home/jniles/code/bhima/node_modules/mysql/lib/protocol/sequences/Query.js:74:10)
  errors     at Protocol._parsePacket (/home/jniles/code/bhima/node_modules/mysql/lib/protocol/Protocol.js:291:23)
  errors     at Parser._parsePacket (/home/jniles/code/bhima/node_modules/mysql/lib/protocol/Parser.js:433:10)
  errors     at Parser.write (/home/jniles/code/bhima/node_modules/mysql/lib/protocol/Parser.js:43:10)
  errors     at Protocol.write (/home/jniles/code/bhima/node_modules/mysql/lib/protocol/Protocol.js:38:16)
  errors     at Socket.<anonymous> (/home/jniles/code/bhima/node_modules/mysql/lib/Connection.js:88:28) {
  errors   code: 'ER_ROW_IS_REFERENCED_2',
  errors   errno: 1451,
  errors   sqlMessage: 'Cannot delete or update a parent row: a foreign key constraint fails (`bhima_test`.`fee_center_distribution`, CONSTRAINT `fee_center_distribution__general_ledger` FOREIGN KEY (`row_uuid`) REFERENCES `general_ledger` (`uuid`))',
  errors   sqlState: '23000',
  errors   index: 0,
  errors   sql: "CALL zUnpostRecord(X'79b0393553c54498a5eca8ca6dfea7ac')"
  errors } +0ms

```

**Comment by jniles** [comment]
We've redesigned cost centers, so it is no longer an issue.
