### ISSUE TITLE
Deactivating a user errors out on IMCK database

### ISSUE THREAD

**Issue by jniles** [Third-Culture-Software/bhima#7422]
I recently did an upgrade of the IMCK database from BHIMA version 1.22.1 to 1.30.2.

As part of the upgrade, I attempted to close out an old user account by deactivating it, which errored out with this message:

```bash
jan 20 00:14:46 bhima-NUC7i3DNKE node[28535]: 2024-01-19T23:14:46.228Z errors #interceptor() Error: ER_TRUNCATED_WRONG_VALUE: Incorrect datetime value: '2021-03-13T22:22:38.000Z' for column 'created_at' at row 1
jan 20 00:14:46 bhima-NUC7i3DNKE node[28535]:     at Sequence._packetToError (/home/bhima/apps/bhima-v1.30.2/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
jan 20 00:14:46 bhima-NUC7i3DNKE node[28535]:     at Query.ErrorPacket (/home/bhima/apps/bhima-v1.30.2/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
jan 20 00:14:46 bhima-NUC7i3DNKE node[28535]:     at Protocol._parsePacket (/home/bhima/apps/bhima-v1.30.2/node_modules/mysql/lib/protocol/Protocol.js:291:23)
jan 20 00:14:46 bhima-NUC7i3DNKE node[28535]:     at Parser._parsePacket (/home/bhima/apps/bhima-v1.30.2/node_modules/mysql/lib/protocol/Parser.js:433:10)
jan 20 00:14:46 bhima-NUC7i3DNKE node[28535]:     at Parser.write (/home/bhima/apps/bhima-v1.30.2/node_modules/mysql/lib/protocol/Parser.js:43:10)
jan 20 00:14:46 bhima-NUC7i3DNKE node[28535]:     at Protocol.write (/home/bhima/apps/bhima-v1.30.2/node_modules/mysql/lib/protocol/Protocol.js:38:16)
jan 20 00:14:46 bhima-NUC7i3DNKE node[28535]:     at Socket.<anonymous> (/home/bhima/apps/bhima-v1.30.2/node_modules/mysql/lib/Connection.js:88:28)
jan 20 00:14:46 bhima-NUC7i3DNKE node[28535]:     at Socket.<anonymous> (/home/bhima/apps/bhima-v1.30.2/node_modules/mysql/lib/Connection.js:526:10)
jan 20 00:14:46 bhima-NUC7i3DNKE node[28535]:     at Socket.emit (node:events:518:28)
jan 20 00:14:46 bhima-NUC7i3DNKE node[28535]:     at addChunk (node:internal/streams/readable:559:12)
jan 20 00:14:46 bhima-NUC7i3DNKE node[28535]:     at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
jan 20 00:14:46 bhima-NUC7i3DNKE node[28535]:     at Readable.push (node:internal/streams/readable:390:5)
jan 20 00:14:46 bhima-NUC7i3DNKE node[28535]:     at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
jan 20 00:14:46 bhima-NUC7i3DNKE node[28535]:     --------------------
jan 20 00:14:46 bhima-NUC7i3DNKE node[28535]:     at Protocol._enqueue (/home/bhima/apps/bhima-v1.30.2/node_modules/mysql/lib/protocol/Protocol.js:144:48)
jan 20 00:14:46 bhima-NUC7i3DNKE node[28535]:     at PoolConnection.query (/home/bhima/apps/bhima-v1.30.2/node_modules/mysql/lib/Connection.js:198:25)
jan 20 00:14:46 bhima-NUC7i3DNKE node[28535]:     at queryConnection (/home/bhima/apps/bhima-v1.30.2/bin/server/lib/db/transaction.js:14:28)
jan 20 00:14:46 bhima-NUC7i3DNKE node[28535]:     at /home/bhima/apps/bhima-v1.30.2/bin/server/lib/db/transaction.js:127:48
jan 20 00:14:46 bhima-NUC7i3DNKE node[28535]:     at Array.map (<anonymous>)
jan 20 00:14:46 bhima-NUC7i3DNKE node[28535]:     at Query.<anonymous> (/home/bhima/apps/bhima-v1.30.2/bin/server/lib/db/transaction.js:127:34)
jan 20 00:14:46 bhima-NUC7i3DNKE node[28535]:     at Query.<anonymous> (/home/bhima/apps/bhima-v1.30.2/node_modules/mysql/lib/Connection.js:526:10)
jan 20 00:14:46 bhima-NUC7i3DNKE node[28535]:     at Query._callback (/home/bhima/apps/bhima-v1.30.2/node_modules/mysql/lib/Connection.js:488:16)
jan 20 00:14:46 bhima-NUC7i3DNKE node[28535]:     at Sequence.end (/home/bhima/apps/bhima-v1.30.2/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
jan 20 00:14:46 bhima-NUC7i3DNKE node[28535]:     at Query._handleFinalResultPacket (/home/bhima/apps/bhima-v1.30.2/node_modules/mysql/lib/protocol/sequences/Query.js:149:8)
jan 20 00:14:46 bhima-NUC7i3DNKE node[28535]:     at Query.OkPacket (/home/bhima/apps/bhima-v1.30.2/node_modules/mysql/lib/protocol/sequences/Query.js:74:10)
jan 20 00:14:46 bhima-NUC7i3DNKE node[28535]:     at Protocol._parsePacket (/home/bhima/apps/bhima-v1.30.2/node_modules/mysql/lib/protocol/Protocol.js:291:23)
jan 20 00:14:46 bhima-NUC7i3DNKE node[28535]:     at Parser._parsePacket (/home/bhima/apps/bhima-v1.30.2/node_modules/mysql/lib/protocol/Parser.js:433:10)
jan 20 00:14:46 bhima-NUC7i3DNKE node[28535]:     at Parser.write (/home/bhima/apps/bhima-v1.30.2/node_modules/mysql/lib/protocol/Parser.js:43:10)
jan 20 00:14:46 bhima-NUC7i3DNKE node[28535]:     at Protocol.write (/home/bhima/apps/bhima-v1.30.2/node_modules/mysql/lib/protocol/Protocol.js:38:16)
jan 20 00:14:46 bhima-NUC7i3DNKE node[28535]:     at Socket.<anonymous> (/home/bhima/apps/bhima-v1.30.2/node_modules/mysql/lib/Connection.js:88:28) {
jan 20 00:14:46 bhima-NUC7i3DNKE node[28535]:   code: 'ER_TRUNCATED_WRONG_VALUE',
jan 20 00:14:46 bhima-NUC7i3DNKE node[28535]:   errno: 1292,
jan 20 00:14:46 bhima-NUC7i3DNKE node[28535]:   sqlMessage: "Incorrect datetime value: '2021-03-13T22:22:38.000Z' for column 'created_at' at row 1",
jan 20 00:14:46 bhima-NUC7i3DNKE node[28535]:   sqlState: '22007',
jan 20 00:14:46 bhima-NUC7i3DNKE node[28535]:   index: 0,
jan 20 00:14:46 bhima-NUC7i3DNKE node[28535]:   sql: "UPDATE user SET `display_name` = 'XXXXX', `username` = 'XXXX', `deactivated` = 1, `enable_external_access` = 0, `created_at` = '2021-03-13T22:22:38.000Z' WHERE id = '14';"
jan 20 00:14:46 bhima-NUC7i3DNKE node[28535]: 2024-01-19T23:14:46.230Z http ::ffff:127.0.0.1 - PUT /users/14 HTTP/1.1 400 72 - 8.362 ms

```

As you can see, there is a date that is being passed to the database a string that is causing the error.  

However, I think this PUT statement is likely doing too much - the only field we need to change is the `deactivated` column, why are we sending the entire `user` object back?

I propose this is fixed by only sending the relevant information back to the server (in this case, the user id and deactivated fields).  Specifically, here:

https://github.com/IMA-WorldHealth/bhima/blob/1ac586befc548aa14f1008a91b76001af137567d/client/src/modules/users/users.js#L124-L141

Instead of sending back the entire `user` object in the update, we can just send back the `{ deactivated : !user.deactivated }` or something of that nature.

**Comment by lomamech** [comment]
I will also take into account the recommendation of this issue
​
